version: '3'

services:
  grokmirror:
    profiles: ["mirroring"]
    userns_mode: keep-id
    build:
      context: .
      dockerfile: ./Containerfile
    environment:
      - HOME=/tmp
      - PI_DATA_DIR=/data
      - GROKMIRROR_MODE=${GROKMIRROR_MODE:-clone}
      - GROKMIRROR_EXTINDEX_ENABLED=${GROKMIRROR_EXTINDEX_ENABLED:-true}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./configs/grokmirror/${GROKMIRROR_MODE:-clone}.conf:/config/grokmirror.conf:z
      - ./configs/pi-configs/:/etc/public-inbox/:z
      - ./data/:/data:z
      - ./scripts:/scripts:z
    # defaults to running in daemon mode. "pull-mirror" option pulls once
    command: grok-pull -v --continuous -c /config/grokmirror.conf
    stop_grace_period: 90s
    restart: on-failure

  indexer:
    profiles: ["manual"]
    userns_mode: keep-id
    build:
      context: .
      dockerfile: ./Containerfile
    environment:
      - HOME=/tmp
      - PI_DATA_DIR=/data
      - PI_CONFIG=/etc/public-inbox/config
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./configs/pi-configs/:/etc/public-inbox/:z
      - ./data/:/data:z
      - ./scripts:/scripts:z
    command: bash /scripts/index-cloned-repos.sh -o ${MIRROR_UPSTREAM_HOST}

  nginx:
    profiles: ["hosting"]
    image: docker.angie.software/angie:minimal
    ports:
      - "${SERVE_HTTP_PORT:-80}:80"
      - "${SERVE_HTTPS_PORT:-443}:443"
      - "${SERVE_NNTP_PORT:-119}:119"
    volumes:
      - ./configs/nginx/angie.conf:/etc/angie/angie.conf:z
      - ./acme:/var/lib/angie/acme:z
      - ./config_template/pi-configs/216dark.css:/var/www/static/theme.css:z
    depends_on:
      - public-inbox
    restart: unless-stopped

  public-inbox:
    profiles: ["hosting"]
    userns_mode: keep-id
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Containerfile
      args:
        USER_ID: '${UID:-1000}'
        GROUP_ID: '${GID:-1000}'
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - HOME=/tmp
      - DEBUG=false
      - PI_CONFIG=/etc/public-inbox/config
      - PI_DATA_DIR=/data
      - IMAP_FOLDER=INBOX
      - IMAP_SSL=true
      - IMAP_INTERVAL=3600
      - SA_MAX_MAIL_SIZE=4096000
    volumes:
      - ./data/:/data/:z
      - ./config_template/pi-configs/216dark.css:/static/theme.css:z
      - ./scripts:/scripts:z
      - ./configs/pi-configs/:/etc/public-inbox/:z
      - ./logs/:/var/log/public-inbox/:z
    command: >
      bash /scripts/start-public-inbox.sh
