user  angie;
worker_processes  16;

error_log  /var/log/angie/error.log notice;
pid        /var/run/angie.pid;

events {
    worker_connections 120;
}

http {
    proxy_cache_path /tmp/angie_cache levels=1:2 keys_zone=local_cache:30m max_size=510m inactive=10d;
    proxy_temp_path /tmp/angie_proxy 1 2;

	  # Upstream for public-inbox HTTP service
    upstream public_inbox {
        server public-inbox:8080;
    }

    # HTTP server 
    server {
        listen 80;
        server_name lore.rcpassos.me;

        server_tokens off;

        # Correctly load mime types
        include /etc/angie/mime.types;

        # Static file serving for theme.css
        location = /static/theme.css {
            alias /var/www/static/theme.css;
            default_type text/css;
        }
        # Proxy all other requests to public-inbox
        location / {
            proxy_pass http://public_inbox;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
